app = "rz-bot"
primary_region = "sin"

[build]

[processes]
  app = "python main.py"

[[services]]
  processes = ["app"]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    method = "get"
    path = "/"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1